services:
  tabeletap-nest:
    container_name: tabletap-nest
    restart: always
    image: node:20.18.1
    ports:
      - 6767:6767
    volumes:
      - ./:/usr/src/tabletap-nest
    working_dir: /usr/src/tabletap-nest

    networks:
      - tabletap-nest-network

    #production
    command: bash -c "npm install pnpm -g && pnpm install && pnpm run start:dev"

networks:
  tabletap-nest-network:
    driver: bridge
